import { Router } from 'express';
import authRoutes from './auth.routes';
import productRoutes from './product.routes';
import orderRoutes from './order.routes';
import cartRoutes from './cart.routes';
import paymentRoutes from './payment.routes';
import userRoutes from './user.routes';
import sellerRoutes from './seller.routes';
import adminRoutes from './admin.routes';
import blogRoutes from './blog.routes';
import categoryRoutes from './category.routes';
import trainingRoutes from './training.routes';
import projectRoutes from './project.routes';
import searchRoutes from './search.routes';
import uploadRoutes from './upload.routes';
import shippingRoutes from './shipping.routes';
import wishlistRoutes from './wishlist.routes';
import newsletterRoutes from './newsletter.routes';
import couponRoutes from './coupon.routes';
import slidesRoutes from './slides.routes';
import miscRoutes from './misc.routes';
import analyticsRoutes from './analytics.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/products', productRoutes);
router.use('/orders', orderRoutes);
router.use('/cart', cartRoutes);
router.use('/payments', paymentRoutes);
router.use('/payment', paymentRoutes);
router.use('/users', userRoutes);
router.use('/user', userRoutes);
router.use('/seller', sellerRoutes);
router.use('/sellers', sellerRoutes);
router.use('/admin', adminRoutes);
router.use('/blog', blogRoutes);
router.use('/categories', categoryRoutes);
router.use('/trainings', trainingRoutes);
router.use('/projects', projectRoutes);
router.use('/search', searchRoutes);
router.use('/upload', uploadRoutes);
router.use('/shipping', shippingRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/coupons', couponRoutes);
router.use('/slides', slidesRoutes);
router.use('/misc', miscRoutes);
router.use('/analytics', analyticsRoutes);

export default router;
